### ISSUE TITLE
fuse-crash-recovery requires an implementation example that does not depend on libfuse

### ISSUE THREAD

**Issue by flying-122** [OpenCloudOS/fuse-extent#3]
Currently fuse-crash-recovery depends on libfuse, but in fact  it has no necessary dependency on libfuse.

**Comment by Zzzz-dot** [comment]
support fuse crash recovery:
1. The current implementationdoes not support fuseblk;
2. Implement the main file system functions (some file system functions are not implemented, such as symlink);
3. At the same time, the current implementation of the crash recovery function does not support multi-thread mode with the --clonefd option enabled, that is, crash recovery under IOCTL (FUSE_DEV_IOC_CLONE) ;
4. If you want your custom file system to support crash recovery, you should implement the interface provided in fuse_crash_recovery_handlers struct to save the memory data structures that need to be saved after the worker process crash.

**Comment by flying-122** [comment]
已完成
